version: '3'

services:

  rabbit:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"   

  microservicoa:
    image: lcarreiro/microservico-a
    ports:
      - 9090:9090

  microservicob:
    depends_on:
      - "rabbit"
    image: lcarreiro/microservico-b

  microservicoc:
    image: lcarreiro/microservico-c
    ports:
      - 9092:9092    